package model

const (
	PERMISSION_SCOPE_SYSTEM = "system"
	PERMISSION_SCOPE_TEAM   = "team"
	PERMISSION_SCOPE_GROUP  = "group"
)

type Permission struct {
	Id    string
	Scope string
}

var PERMISSION_CREATE_POST *Permission
var PERMISSION_CREATE_TEAM *Permission
var PERMISSION_READ_OTHERS_TEAMS *Permission
var PERMISSION_EDIT_POST *Permission
var PERMISSION_EDIT_OTHERS_POSTS *Permission
var PERMISSION_DELETE_POST *Permission
var PERMISSION_DELETE_OTHERS_POSTS *Permission
var PERMISSION_DELETE_USER *Permission
var PERMISSION_DELETE_OTHER_USERS *Permission
var PERMISSION_EDIT_OTHER_USERS *Permission
var PERMISSION_EDIT_OTHER_USERS_PASSWORD *Permission
var PERMISSION_VOTE_POST *Permission
var PERMISSION_FLAG_POST *Permission
var PERMISSION_READ_OTHERS_INBOX_MESSAGES *Permission
var PERMISSION_SET_READ_OTHERS_INBOX_MESSAGES *Permission
var PERMISSION_READ_OTHERS_USER_POINT_HISTORY *Permission
var PERMISSION_READ_OTHERS_VOTES *Permission
var PERMISSION_FAVORITE_POST *Permission
var PERMISSION_LOCK_POST *Permission
var PERMISSION_PROTECT_POST *Permission
var PERMISSION_SUSPEND_USER *Permission
var PERMISSION_EDIT_USER_TYPE *Permission

var PERMISSION_MANAGE_TEAM *Permission
var PERMISSION_VIEW_TEAM *Permission
var PERMISSION_ADD_USER_TO_TEAM *Permission
var PERMISSION_INVITE_USER_TO_TEAM *Permission
var PERMISSION_REMOVE_USER_FROM_TEAM *Permission
var PERMISSION_CREATE_GROUP *Permission
var PERMISSION_CREATE_COLLECTION *Permission
var PERMISSION_DELETE_COLLECTION *Permission
var PERMISSION_LIST_TEAM_GROUPS *Permission
var PERMISSION_VIEW_TEAM_POST *Permission
var PERMISSION_CREATE_TEAM_POST *Permission
var PERMISSION_EDIT_TEAM_POST *Permission
var PERMISSION_EDIT_OTHERS_TEAM_POSTS *Permission
var PERMISSION_VOTE_TEAM_POST *Permission
var PERMISSION_FLAG_TEAM_POST *Permission
var PERMISSION_FAVORITE_TEAM_POST *Permission
var PERMISSION_DELETE_TEAM_POST *Permission
var PERMISSION_DELETE_OTHERS_TEAM_POSTS *Permission
var PERMISSION_READ_GROUP *Permission
var PERMISSION_JOIN_GROUPS *Permission
var PERMISSION_MANAGE_COLLECTION_POSTS *Permission

var PERMISSION_MANAGE_GROUP_PROPERTIES *Permission
var PERMISSION_MANAGE_GROUP_MEMBERS *Permission
var PERMISSION_MANAGE_GROUP_MEMBER_TYPE *Permission
var PERMISSION_MANAGE_GROUP *Permission

var ALL_PERMISSIONS []*Permission

func initializePermissions() {
	PERMISSION_CREATE_POST = &Permission{
		"create_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_CREATE_TEAM = &Permission{
		"create_team",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_READ_OTHERS_TEAMS = &Permission{
		"read_others_teams",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_EDIT_POST = &Permission{
		"edit_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_EDIT_OTHERS_POSTS = &Permission{
		"edit_others_posts",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_DELETE_POST = &Permission{
		"delete_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_DELETE_OTHERS_POSTS = &Permission{
		"delete_others_posts",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_DELETE_USER = &Permission{
		"delete_user",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_DELETE_OTHER_USERS = &Permission{
		"delete_other_users",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_EDIT_OTHER_USERS = &Permission{
		"edit_other_users",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_EDIT_OTHER_USERS_PASSWORD = &Permission{
		"edit_other_users",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_VOTE_POST = &Permission{
		"vote_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_FLAG_POST = &Permission{
		"flag_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_READ_OTHERS_INBOX_MESSAGES = &Permission{
		"read_others_inbox_messages",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_SET_READ_OTHERS_INBOX_MESSAGES = &Permission{
		"set_read_others_inbox_messages",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_READ_OTHERS_USER_POINT_HISTORY = &Permission{
		"read_others_user_point_history",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_READ_OTHERS_VOTES = &Permission{
		"read_others_votes",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_FAVORITE_POST = &Permission{
		"favorite_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_LOCK_POST = &Permission{
		"lock_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_PROTECT_POST = &Permission{
		"protect_post",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_SUSPEND_USER = &Permission{
		"suspend_user",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_EDIT_USER_TYPE = &Permission{
		"edit_user_type",
		PERMISSION_SCOPE_SYSTEM,
	}

	PERMISSION_MANAGE_TEAM = &Permission{
		"manage_team",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_VIEW_TEAM = &Permission{
		"view_team",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_ADD_USER_TO_TEAM = &Permission{
		"add_user_to_team",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_INVITE_USER_TO_TEAM = &Permission{
		"invite_user_to_team",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_REMOVE_USER_FROM_TEAM = &Permission{
		"remove_user_from_team",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_CREATE_GROUP = &Permission{
		"create_group",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_CREATE_COLLECTION = &Permission{
		"create_collection",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_DELETE_COLLECTION = &Permission{
		"delete_collection",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_LIST_TEAM_GROUPS = &Permission{
		"list_team_groups",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_VIEW_TEAM_POST = &Permission{
		"view_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_CREATE_TEAM_POST = &Permission{
		"create_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_EDIT_TEAM_POST = &Permission{
		"edit_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_EDIT_OTHERS_TEAM_POSTS = &Permission{
		"edit_others_team_posts",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_VOTE_TEAM_POST = &Permission{
		"vote_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_FLAG_TEAM_POST = &Permission{
		"flag_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_FAVORITE_TEAM_POST = &Permission{
		"favorite_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_DELETE_TEAM_POST = &Permission{
		"delete_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_DELETE_OTHERS_TEAM_POSTS = &Permission{
		"delete_others_team_post",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_READ_GROUP = &Permission{
		"read_group",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_JOIN_GROUPS = &Permission{
		"join_groups",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_MANAGE_COLLECTION_POSTS = &Permission{
		"manage_collection_posts",
		PERMISSION_SCOPE_TEAM,
	}

	PERMISSION_MANAGE_GROUP_PROPERTIES = &Permission{
		"manage_group_properties",
		PERMISSION_SCOPE_GROUP,
	}

	PERMISSION_MANAGE_GROUP_MEMBERS = &Permission{
		"manage_group_members",
		PERMISSION_SCOPE_GROUP,
	}

	PERMISSION_MANAGE_GROUP_MEMBER_TYPE = &Permission{
		"manage_group_member_type",
		PERMISSION_SCOPE_GROUP,
	}

	PERMISSION_MANAGE_GROUP = &Permission{
		"manage_group",
		PERMISSION_SCOPE_GROUP,
	}

	ALL_PERMISSIONS = []*Permission{
		PERMISSION_CREATE_POST,
		PERMISSION_CREATE_TEAM,
		PERMISSION_READ_OTHERS_TEAMS,
		PERMISSION_EDIT_POST,
		PERMISSION_EDIT_OTHERS_POSTS,
		PERMISSION_DELETE_POST,
		PERMISSION_DELETE_OTHERS_POSTS,
		PERMISSION_DELETE_USER,
		PERMISSION_DELETE_OTHER_USERS,
		PERMISSION_EDIT_OTHER_USERS,
		PERMISSION_EDIT_OTHER_USERS_PASSWORD,
		PERMISSION_VOTE_POST,
		PERMISSION_FLAG_POST,
		PERMISSION_READ_OTHERS_INBOX_MESSAGES,
		PERMISSION_SET_READ_OTHERS_INBOX_MESSAGES,
		PERMISSION_READ_OTHERS_USER_POINT_HISTORY,
		PERMISSION_READ_OTHERS_VOTES,
		PERMISSION_FAVORITE_POST,
		PERMISSION_PROTECT_POST,
		PERMISSION_SUSPEND_USER,
		PERMISSION_EDIT_USER_TYPE,
		PERMISSION_MANAGE_TEAM,
		PERMISSION_VIEW_TEAM,
		PERMISSION_ADD_USER_TO_TEAM,
		PERMISSION_INVITE_USER_TO_TEAM,
		PERMISSION_REMOVE_USER_FROM_TEAM,
		PERMISSION_CREATE_GROUP,
		PERMISSION_CREATE_COLLECTION,
		PERMISSION_DELETE_COLLECTION,
		PERMISSION_LIST_TEAM_GROUPS,
		PERMISSION_VIEW_TEAM_POST,
		PERMISSION_CREATE_TEAM_POST,
		PERMISSION_EDIT_TEAM_POST,
		PERMISSION_EDIT_OTHERS_TEAM_POSTS,
		PERMISSION_VOTE_TEAM_POST,
		PERMISSION_FLAG_TEAM_POST,
		PERMISSION_FAVORITE_TEAM_POST,
		PERMISSION_DELETE_TEAM_POST,
		PERMISSION_DELETE_OTHERS_TEAM_POSTS,
		PERMISSION_READ_GROUP,
		PERMISSION_JOIN_GROUPS,
		PERMISSION_MANAGE_COLLECTION_POSTS,
		PERMISSION_MANAGE_GROUP_PROPERTIES,
		PERMISSION_MANAGE_GROUP_MEMBERS,
		PERMISSION_MANAGE_GROUP_MEMBER_TYPE,
		PERMISSION_MANAGE_GROUP,
	}
}

func init() {
	initializePermissions()
}
