package model

type Role struct {
	Name        string
	Permissions []string
}

var ROLE_NORMAL *Role
var ROLE_MODERATOR *Role
var ROLE_ADMIN *Role
var ROLE_TEAM_MEMBER_TYPE_NORMAL *Role
var ROLE_TEAM_MEMBER_TYPE_ADMIN *Role
var ROLE_GROUP_MEMBER_TYPE_NORMAL *Role
var ROLE_GROUP_MEMBER_TYPE_ADMIN *Role

var ALL_ROLES []*Role

func initializeRoles() {
	ROLE_NORMAL = &Role{
		Name: USER_TYPE_NORMAL,
		Permissions: []string{
			PERMISSION_CREATE_POST.Id,
			PERMISSION_CREATE_TEAM.Id,
			PERMISSION_EDIT_POST.Id,
			PERMISSION_DELETE_POST.Id,
			PERMISSION_DELETE_USER.Id,
			PERMISSION_VOTE_POST.Id,
			PERMISSION_FLAG_POST.Id,
			PERMISSION_FAVORITE_POST.Id,
			PERMISSION_MANAGE_OAUTH.Id,
		},
	}

	// TODO: teamを考慮し再修正
	ROLE_MODERATOR = &Role{
		Name: USER_TYPE_MODERATOR,
		Permissions: append(
			[]string{
				PERMISSION_DELETE_OTHERS_POSTS.Id,
				PERMISSION_LOCK_POST.Id,
				PERMISSION_PROTECT_POST.Id,
				PERMISSION_SUSPEND_USER.Id,
				PERMISSION_CREATE_REVIEW_VOTES.Id,
				PERMISSION_COMPLETE_REVIEW_VOTES.Id,
			},
			ROLE_NORMAL.Permissions...,
		),
	}

	ROLE_GROUP_MEMBER_TYPE_NORMAL = &Role{
		Name:        "group_" + GROUP_MEMBER_TYPE_NORMAL,
		Permissions: []string{},
	}

	ROLE_GROUP_MEMBER_TYPE_ADMIN = &Role{
		Name: "group_" + GROUP_MEMBER_TYPE_ADMIN,
		Permissions: append(
			[]string{
				PERMISSION_MANAGE_GROUP_PROPERTIES.Id,
				PERMISSION_MANAGE_GROUP_MEMBERS.Id,
				PERMISSION_MANAGE_GROUP_MEMBER_TYPE.Id,
				PERMISSION_MANAGE_GROUP.Id,
			},
			ROLE_GROUP_MEMBER_TYPE_NORMAL.Permissions...,
		),
	}

	ROLE_TEAM_MEMBER_TYPE_NORMAL = &Role{
		Name: "team_" + TEAM_MEMBER_TYPE_NORMAL,
		Permissions: []string{
			PERMISSION_VIEW_TEAM.Id,
			PERMISSION_LIST_TEAM_GROUPS.Id,
			PERMISSION_VIEW_TEAM_POST.Id,
			PERMISSION_CREATE_TEAM_POST.Id,
			PERMISSION_EDIT_TEAM_POST.Id,
			PERMISSION_DELETE_TEAM_POST.Id,
			PERMISSION_VOTE_TEAM_POST.Id,
			PERMISSION_FLAG_TEAM_POST.Id,
			PERMISSION_FAVORITE_TEAM_POST.Id,
			PERMISSION_READ_GROUP.Id,
		},
	}

	ROLE_TEAM_MEMBER_TYPE_ADMIN = &Role{
		Name: "team_" + TEAM_MEMBER_TYPE_ADMIN,
		Permissions: append(
			append(
				[]string{
					PERMISSION_ADD_USER_TO_TEAM.Id,
					PERMISSION_INVITE_USER_TO_TEAM.Id,
					PERMISSION_REMOVE_USER_FROM_TEAM.Id,
					PERMISSION_CREATE_GROUP.Id,
					PERMISSION_JOIN_GROUPS.Id,
					PERMISSION_MANAGE_COLLECTION_POSTS.Id,
					PERMISSION_MANAGE_WEBHOOKS.Id,
					PERMISSION_MANAGE_OTHERS_WEBHOOKS.Id,
					PERMISSION_CREATE_COLLECTION.Id,
					PERMISSION_DELETE_COLLECTION.Id,
					PERMISSION_EDIT_OTHERS_TEAM_POSTS.Id,
					PERMISSION_DELETE_OTHERS_TEAM_POSTS.Id,
					PERMISSION_MANAGE_TEAM.Id,
				},
				ROLE_TEAM_MEMBER_TYPE_NORMAL.Permissions...,
			),
			ROLE_GROUP_MEMBER_TYPE_ADMIN.Permissions...,
		),
	}

	ROLE_ADMIN = &Role{
		Name: USER_TYPE_ADMIN,
		Permissions: append(
			append(
				[]string{
					PERMISSION_READ_OTHERS_TEAMS.Id,
					PERMISSION_EDIT_OTHERS_POSTS.Id,
					PERMISSION_EDIT_OTHER_USERS.Id,
					PERMISSION_EDIT_OTHER_USERS_PASSWORD.Id,
					PERMISSION_EDIT_USER_TYPE.Id,
					PERMISSION_CREATE_REVIEW_TAGS.Id,
					PERMISSION_DELETE_OTHER_USERS.Id,
					PERMISSION_READ_OTHERS_INBOX_MESSAGES.Id,
					PERMISSION_SET_READ_OTHERS_INBOX_MESSAGES.Id,
					PERMISSION_READ_OTHERS_USER_POINT_HISTORY.Id,
					PERMISSION_READ_OTHERS_VOTES.Id,
				},
				ROLE_MODERATOR.Permissions...,
			),
			ROLE_TEAM_MEMBER_TYPE_ADMIN.Permissions...,
		),
	}

	ALL_ROLES = []*Role{
		ROLE_NORMAL,
		ROLE_MODERATOR,
		ROLE_GROUP_MEMBER_TYPE_NORMAL,
		ROLE_GROUP_MEMBER_TYPE_ADMIN,
		ROLE_TEAM_MEMBER_TYPE_NORMAL,
		ROLE_TEAM_MEMBER_TYPE_ADMIN,
		ROLE_ADMIN,
	}
}

func init() {
	initializeRoles()
}
